/* eslint-disable @typescript-eslint/naming-convention */
import { TenrxEnumState } from './TenrxEnums.js';

export const TenrxStateIdToStateName = {
  [TenrxEnumState.California]: 'California',
  [TenrxEnumState.Florida]: 'Florida',
  [TenrxEnumState.Alaska]: 'Alaska',
  [TenrxEnumState.Arizona]: 'Arizona',
  [TenrxEnumState.Arkansas]: 'Arkansas',
  [TenrxEnumState.Colorado]: 'Colorado',
  [TenrxEnumState.Connecticut]: 'Connecticut',
  [TenrxEnumState.Delaware]: 'Delaware',
  [TenrxEnumState.DistrictOfColumbia]: 'District Of Columbia',
  [TenrxEnumState.Georgia]: 'Georgia',
  [TenrxEnumState.Hawaii]: 'Hawaii',
  [TenrxEnumState.Idaho]: 'Idaho',
  [TenrxEnumState.Illinois]: 'Illinois',
  [TenrxEnumState.Indiana]: 'Indiana',
  [TenrxEnumState.Iowa]: 'Iowa',
  [TenrxEnumState.Kansas]: 'Kansas',
  [TenrxEnumState.Kentucky]: 'Kentucky',
  [TenrxEnumState.Louisiana]: 'Louisiana',
  [TenrxEnumState.Maine]: 'Maine',
  [TenrxEnumState.Maryland]: 'Maryland',
  [TenrxEnumState.Massachusetts]: 'Massachusetts',
  [TenrxEnumState.Michigan]: 'Michigan',
  [TenrxEnumState.Minnesota]: 'Minnesota',
  [TenrxEnumState.Mississippi]: 'Mississippi',
  [TenrxEnumState.Missouri]: 'Missouri',
  [TenrxEnumState.Montana]: 'Montana',
  [TenrxEnumState.Nebraska]: 'Nebraska',
  [TenrxEnumState.Nevada]: 'Nevada',
  [TenrxEnumState.NewHampshire]: 'New Hampshire',
  [TenrxEnumState.NewJersey]: 'New Jersey',
  [TenrxEnumState.NewMexico]: 'New Mexico',
  [TenrxEnumState.NewYork]: 'New York',
  [TenrxEnumState.NorthCarolina]: 'North Carolina',
  [TenrxEnumState.NorthDakota]: 'North Dakota',
  [TenrxEnumState.Ohio]: 'Ohio',
  [TenrxEnumState.Oklahoma]: 'Oklahoma',
  [TenrxEnumState.Oregon]: 'Oregon',
  [TenrxEnumState.Pennsylvania]: 'Pennsylvania',
  [TenrxEnumState.PuertoRico]: 'Puerto Rico',
  [TenrxEnumState.RhodeIsland]: 'Rhode Island',
  [TenrxEnumState.SouthCarolina]: 'South Carolina',
  [TenrxEnumState.SouthDakota]: 'South Dakota',
  [TenrxEnumState.Tennessee]: 'Tennessee',
  [TenrxEnumState.Texas]: 'Texas',
  [TenrxEnumState.Utah]: 'Utah',
  [TenrxEnumState.Vermont]: 'Vermont',
  [TenrxEnumState.Virginia]: 'Virginia',
  [TenrxEnumState.Washington]: 'Washington',
  [TenrxEnumState.WestVirginia]: 'West Virginia',
  [TenrxEnumState.Wisconsin]: 'Wisconsin',
  [TenrxEnumState.Wyoming]: 'Wyoming',
  [TenrxEnumState.Alabama]: 'Alabama',
};

// eslint-disable-next-line @typescript-eslint/naming-convention
export const TenrxStateNameToStateId: Record<string, TenrxEnumState> = {
  California: TenrxEnumState.California,
  Florida: TenrxEnumState.Florida,
  Alaska: TenrxEnumState.Alaska,
  Arizona: TenrxEnumState.Arizona,
  Arkansas: TenrxEnumState.Arkansas,
  Colorado: TenrxEnumState.Colorado,
  Connecticut: TenrxEnumState.Connecticut,
  Delaware: TenrxEnumState.Delaware,
  'District Of Columbia': TenrxEnumState.DistrictOfColumbia,
  Georgia: TenrxEnumState.Georgia,
  Hawaii: TenrxEnumState.Hawaii,
  Idaho: TenrxEnumState.Idaho,
  Illinois: TenrxEnumState.Illinois,
  Indiana: TenrxEnumState.Indiana,
  Iowa: TenrxEnumState.Iowa,
  Kansas: TenrxEnumState.Kansas,
  Kentucky: TenrxEnumState.Kentucky,
  Louisiana: TenrxEnumState.Louisiana,
  Maine: TenrxEnumState.Maine,
  Maryland: TenrxEnumState.Maryland,
  Massachusetts: TenrxEnumState.Massachusetts,
  Michigan: TenrxEnumState.Michigan,
  Minnesota: TenrxEnumState.Minnesota,
  Mississippi: TenrxEnumState.Mississippi,
  Missouri: TenrxEnumState.Missouri,
  Montana: TenrxEnumState.Montana,
  Nebraska: TenrxEnumState.Nebraska,
  Nevada: TenrxEnumState.Nevada,
  'New Hampshire': TenrxEnumState.NewHampshire,
  'New Jersey': TenrxEnumState.NewJersey,
  'New Mexico': TenrxEnumState.NewMexico,
  'New York': TenrxEnumState.NewYork,
  'North Carolina': TenrxEnumState.NorthCarolina,
  'North Dakota': TenrxEnumState.NorthDakota,
  Ohio: TenrxEnumState.Ohio,
  Oklahoma: TenrxEnumState.Oklahoma,
  Oregon: TenrxEnumState.Oregon,
  Pennsylvania: TenrxEnumState.Pennsylvania,
  'Puerto Rico': TenrxEnumState.PuertoRico,
  'Rhode Island': TenrxEnumState.RhodeIsland,
  'South Carolina': TenrxEnumState.SouthCarolina,
  'South Dakota': TenrxEnumState.SouthDakota,
  Tennessee: TenrxEnumState.Tennessee,
  Texas: TenrxEnumState.Texas,
  Utah: TenrxEnumState.Utah,
  Vermont: TenrxEnumState.Vermont,
  Virginia: TenrxEnumState.Virginia,
  Washington: TenrxEnumState.Washington,
  'West Virginia': TenrxEnumState.WestVirginia,
  Wisconsin: TenrxEnumState.Wisconsin,
  Wyoming: TenrxEnumState.Wyoming,
  Alabama: TenrxEnumState.Alabama,
};
