image: csscloudservices/dotnetaws:latest

cache:
  paths:
    - node_modules/

stages:
  - publish
  - lint

publish:
  stage: publish
  script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/8/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm config set unsafe-perm true
    - npm ci
    - npm publish
  only:
    - tags

lint:
  stage: lint
  script:
    - CI=true npm ci
    - npm run lint
  only:
    - merge_requests
